<script>
;(function(){
function boot(t){if(window._thyqPart2Inited)return;if(typeof t.show!=="function"){console.warn("[thyq] part2: show not ready, need link_intercept_1b before this");return}window._thyqPart2Inited=1;var Op=t.Op,go=t.go,hid=t.hid,show=t.show,S=sessionStorage;
function out(h){if(!h||h[0]==="#"||h.startsWith("javascript:"))return false;var x=go(h);return x&&x!==location.origin}
function getOff(e){var el=e.target;while(el&&el!==document.body){var href=(el.getAttribute&&el.getAttribute("href"))||(el.getAttribute&&el.getAttribute("data-href"));if(el.href)href=href||el.href;if(href&&out(href)){var ln=el.tagName==="A"?el:(el.closest&&el.closest("a[href]"));var nt=ln&&(ln.target==="_blank"||(ln.getAttribute&&ln.getAttribute("target")==="_blank"));return{url:el.href?el.href:(function(){try{return new URL(href,location.origin).href}catch(_){return href}})(),newTab:!!nt}}el=el.parentElement}var a=e.target.closest&&e.target.closest("a[href]");if(a&&out(a.getAttribute("href")||a.href))return{url:a.href,newTab:!!(a.target==="_blank"||(a.getAttribute&&a.getAttribute("target")==="_blank"))};return null}
function nav(u,nt){if(nt==="true"){var w=window.open(u,"_blank","noopener,noreferrer");if(!w)location.href=u}else location.href=u}
window.thyquidityConfirmOfframp=function(m){if(window._thyqNavDone)return;var u=S.getItem(Op),nt=S.getItem(Op+"_newtab");S.removeItem(Op);S.removeItem(Op+"_newtab");var el=m||document.querySelector("[data-offramp-modal],#offramp-modal");if(!u&&el){var e=el;while(e&&e!==document.body){u=u||e.getAttribute("data-continue-url");if(e.getAttribute("data-continue-newtab")==="true")nt="true";e=e.parentElement}}hid(el);if(u){window._thyqNavDone=1;nav(u,nt);setTimeout(function(){window._thyqNavDone=0},300)}};
window.thyquidityCancelOfframp=function(m){S.removeItem(Op);S.removeItem(Op+"_newtab");var el=m||document.querySelector("[data-offramp-modal],#offramp-modal");hid(el)};
function storeFromTrigger(e){var el=e.target;while(el&&el!==document.body){var u=el.getAttribute&&el.getAttribute("data-offramp-url");if(u){var nt=el.getAttribute("data-offramp-newtab")==="true";S.setItem(Op,u);S.setItem(Op+"_newtab",nt?"true":"false");return}el=el.parentElement}}
function hdlOff(e){storeFromTrigger(e);var r=getOff(e);if(!r)return;e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();S.setItem(Op+"_newtab",r.newTab?"true":"false");show("[data-offramp-modal],#offramp-modal",r.url,Op)}
document.addEventListener("mousedown",hdlOff,true);document.addEventListener("pointerdown",hdlOff,true);document.addEventListener("click",hdlOff,true);}
if(window._thyq&&window._thyq.show)boot(window._thyq);else{var n=0;function chk(){var t=window._thyq;if(t&&typeof t.show==="function"){boot(t);return}if(++n<50)setTimeout(chk,50);else console.warn("[thyq] part2: part1 not found (need link_intercept_1a + 1b before this)")}chk()}
})();
</script>
