<script>
;(function(){
var t=window._thyq;if(!t)return;
function show(sel,u,k){sessionStorage.setItem(k,u);var m=document.querySelector(sel);if(!m){var fn=window._thyqInjectFallback;if(fn){t.Dbg("Framer overlay not in DOM, using fallback modal");m=fn()}else t.Dbg("fallback not loaded")}if(!m)return;if(typeof m.showModal==="function"){m.showModal();return}var e=m.parentElement;var z="9999";while(e&&e!==document.body){var s=getComputedStyle(e);if(s.position==="fixed"||s.position==="absolute"){e.style.display="flex";e.style.visibility="visible";e.style.pointerEvents="auto";e.style.zIndex=z}e=e.parentElement}m.style.cssText="display:flex;visibility:visible;opacity:1;pointer-events:auto;z-index:"+z}
t.show=show;
window.thyquidityConfirmHcp=function(m){var u=sessionStorage.getItem(t.Hp);sessionStorage.removeItem(t.Hp);sessionStorage.setItem(t.V,"true");var el=m||document.querySelector("[data-hcp-modal],#hcp-modal")||document.querySelector("[data-offramp-modal],#offramp-modal");t.Dbg("ConfirmHcp",u);t.hid(el);if(u)location.href=u};
window.thyquidityCancelHcp=function(m){t.Dbg("CancelHcp");sessionStorage.removeItem(t.Hp);if(t.ih(t.gp()))sessionStorage.setItem(t.V,"true");var el=m||document.querySelector("[data-hcp-modal],#hcp-modal")||document.querySelector("[data-offramp-modal],#offramp-modal");t.hid(el)};
function getHcp(e){function ck(h){if(!h||typeof h!=="string")return null;if(h[0]==="#")return null;try{var u=new URL(h,location.origin);if(u.origin!==location.origin)return null;var p=u.pathname.replace(/\/$/,"")||"/";return t.H.some(function(b){return p===b||p.indexOf(b+"/")===0})?u.href:null}catch(_){return null}}var el=e.target;while(el&&el!==document.body){var h=(el.getAttribute&&(el.getAttribute("href")||el.getAttribute("data-href")))||(el.href||"");if(h){var r=ck(h);if(r)return r}el=el.parentElement}var a=e.target&&e.target.closest&&e.target.closest("a[href]");return a?ck(a.getAttribute("href")||a.href):null}
function storeHcpTrigger(e){var el=e.target;while(el&&el!==document.body){var h=el.getAttribute&&el.getAttribute("data-hcp-url");if(h&&!t.ih(t.gp())&&!sessionStorage.getItem(t.V)){sessionStorage.setItem(t.Hp,h);sessionStorage.removeItem(t.Op);t.Dbg("HCP trigger store",h);return}el=el.parentElement}}
function hdlHcp(e){storeHcpTrigger(e);var h=getHcp(e);if(!h)return;var p=t.gp(),onHcp=t.ih(p),visited=sessionStorage.getItem(t.V);t.Dbg("hdl "+e.type+" HCP link",{url:h,path:p,onHcp:onHcp,visited:!!visited});if(!onHcp&&!visited){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();sessionStorage.setItem(t.Hp,h);sessionStorage.removeItem(t.Op);t.Dbg("HCP modal SHOW",h);showHcpModal()}else{t.Dbg("HCP skipped",onHcp?"on HCP page":"already visited")}}
function fb(){var w=window,d=document.createElement("dialog");d.id="thyq-offramp-fallback";var o=document.getElementById(d.id);if(o)o.remove();d.setAttribute("data-offramp-modal","true");d.setAttribute("data-hcp-modal","true");d.style.cssText="border:none;border-radius:8px;padding:24px;max-width:360px;box-shadow:0 4px 24px rgba(0,0,0,0.3)";d.innerHTML='<p style="margin:0 0 16px;font-size:16px">You are entering the Healthcare Professional section.</p><div style="display:flex;gap:12px;justify-content:flex-end"><button type="button" data-thyq-fb-cancel>Cancel</button><button type="button" data-thyq-fb-confirm>Continue</button></div>';var c=d.querySelector("[data-thyq-fb-cancel]"),x=d.querySelector("[data-thyq-fb-confirm]");c.onclick=function(e){e.preventDefault();d.close();if(w.thyquidityCancelHcp)w.thyquidityCancelHcp(d)};x.onclick=function(e){e.preventDefault();d.close();if(w.thyquidityConfirmHcp)w.thyquidityConfirmHcp(d)};document.body.appendChild(d);d.showModal();return d}
function showHcpModal(){var m=document.querySelector("[data-hcp-modal],#hcp-modal")||document.querySelector("[data-offramp-modal],#offramp-modal");if(!m){var fn=window._thyqInjectFallback;m=fn?fn("hcp"):fb()}if(m){var el=m.parentElement,z="9999";while(el&&el!==document.body){var s=getComputedStyle(el);if(s.position==="fixed"){el.style.display="flex";el.style.visibility="visible";el.style.pointerEvents="auto";el.style.zIndex=z}el=el.parentElement}if(typeof m.showModal==="function")m.showModal();else m.style.cssText="display:flex;visibility:visible;opacity:1;pointer-events:auto;z-index:"+z}}
function init(){if(window._thyqInited)return;window._thyqInited=1;var p=t.gp(),onHcp=t.ih(p),visited=sessionStorage.getItem(t.V);if(onHcp){if(!visited){sessionStorage.setItem(t.Hp,location.href);t.Dbg("init on HCP page, first visit - show modal");showHcpModal()}else{sessionStorage.setItem(t.V,"true");t.Dbg("init part1 on HCP page",p)}}t.Dbg("init part1: mousedown, pointerdown, click");document.addEventListener("mousedown",hdlHcp,true);document.addEventListener("pointerdown",hdlHcp,true);document.addEventListener("click",hdlHcp,true)}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init();
})();
</script>
