<script>
(function(){
var Op="thyquidity_pending_offramp_url",Hp="thyquidity_pending_hcp_url",V="thyquidity_hcp_visited",H=["/hcp","/healthcare"],S=sessionStorage;
function g(h){try{return new URL(h,location.origin).origin}catch(_){return null}}
function o(h){if(!h||h[0]==="#"||h.startsWith("javascript:"))return false;var x=g(h);return x&&x!==location.origin}
function ih(p){p=(p||"").replace(/\/$/,"")||"/";return H.some(function(b){return p===b||p.indexOf(b+"/")===0})}
function gp(){var p=(location.pathname||"").replace(/\/$/,"")||"/";if(p!=="/")return p;var h=(location.hash||"").replace(/^#!?/,"");return h&&h[0]==="/"?h.replace(/\/$/,"")||"/":p}
function hid(m){if(!m)return;m.style.cssText="display:none!important;visibility:hidden!important;pointer-events:none!important;opacity:0!important";var e=m.parentElement;while(e&&e!==document.body){var s=getComputedStyle(e);if(s.position==="fixed"||s.position==="absolute"){e.style.setProperty("display","none","important");e.style.pointerEvents="none"}e=e.parentElement}}
function sh(sel,u,k){S.setItem(k,u);var m=document.querySelector(sel);if(m){var e=m.parentElement;while(e&&e!==document.body){var s=getComputedStyle(e);if(s.position==="fixed"){e.style.display="flex";e.style.visibility="visible";e.style.pointerEvents="auto"}e=e.parentElement}m.style.cssText="display:flex;visibility:visible;opacity:1;pointer-events:auto"}}
window.thyquidityConfirmOfframp=function(m){var u=S.getItem(Op),nt=S.getItem(Op+"_newtab");S.removeItem(Op);S.removeItem(Op+"_newtab");var el=m||document.querySelector("[data-offramp-modal],#offramp-modal");if(!u&&el){var e=el;while(e&&e!==document.body){u=u||e.getAttribute("data-continue-url");if(e.getAttribute("data-continue-newtab")==="true")nt="true";e=e.parentElement}}hid(el);if(u){if(nt==="true"){var w=window.open(u,"_blank","noopener,noreferrer");if(!w)location.href=u}else location.href=u}};
window.thyquidityCancelOfframp=function(m){S.removeItem(Op);S.removeItem(Op+"_newtab");var el=m||document.querySelector("[data-offramp-modal],#offramp-modal");hid(el)};
window.thyquidityConfirmHcp=function(m){var u=S.getItem(Hp);S.removeItem(Hp);S.setItem(V,"true");var el=m||document.querySelector("[data-hcp-modal],#hcp-modal")||document.querySelector("[data-offramp-modal],#offramp-modal");hid(el);if(u)location.href=u};
window.thyquidityCancelHcp=function(m){S.removeItem(Hp);var el=m||document.querySelector("[data-hcp-modal],#hcp-modal")||document.querySelector("[data-offramp-modal],#offramp-modal");hid(el)};
function getOff(e){var el=e.target;while(el&&el!==document.body){var href=(el.getAttribute&&el.getAttribute("href"))||(el.getAttribute&&el.getAttribute("data-href"));if(el.href)href=href||el.href;if(href&&o(href)){var ln=el.tagName==="A"?el:(el.closest&&el.closest("a[href]"));var nt=ln&&(ln.target==="_blank"||(ln.getAttribute&&ln.getAttribute("target")==="_blank"));return{url:el.href?el.href:(function(){try{return new URL(href,location.origin).href}catch(_){return href}})(),newTab:!!nt}}el=el.parentElement}var a=e.target.closest&&e.target.closest("a[href]");if(a&&o(a.getAttribute("href")||a.href))return{url:a.href,newTab:!!(a.target==="_blank"||(a.getAttribute&&a.getAttribute("target")==="_blank"))};return null}
function getHcp(e){function ck(h){if(!h||typeof h!=="string")return null;if(h[0]==="#")return null;try{var u=new URL(h,location.origin);if(u.origin!==location.origin)return null;var p=u.pathname.replace(/\/$/,"")||"/";return H.some(function(b){return p===b||p.indexOf(b+"/")===0})?u.href:null}catch(_){return null}}var el=e.target;while(el&&el!==document.body){var h=(el.getAttribute&&(el.getAttribute("href")||el.getAttribute("data-href")))||(el.href||"");if(h){var r=ck(h);if(r)return r}el=el.parentElement}var a=e.target&&e.target.closest&&e.target.closest("a[href]");return a?ck(a.getAttribute("href")||a.href):null}
function hdl(e){var h=getHcp(e);if(h&&!ih(gp())&&!S.getItem(V)){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();S.setItem(Hp,h);S.removeItem(Op);var m=document.querySelector("[data-hcp-modal],#hcp-modal")||document.querySelector("[data-offramp-modal],#offramp-modal");if(m){var el=m.parentElement;while(el&&el!==document.body){var s=getComputedStyle(el);if(s.position==="fixed"){el.style.display="flex";el.style.visibility="visible";el.style.pointerEvents="auto"}el=el.parentElement}m.style.cssText="display:flex;visibility:visible;opacity:1;pointer-events:auto"}return}var r=getOff(e);if(r){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();S.setItem(Op+"_newtab",r.newTab?"true":"false");sh("[data-offramp-modal],#offramp-modal",r.url,Op)}}
function init(){if(ih(gp()))S.setItem(V,"true");document.addEventListener("mousedown",hdl,true);document.addEventListener("pointerdown",hdl,true);document.addEventListener("click",hdl,true)}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init();
})();
</script>
