-- Seed interim joint + statutory committees for the 2026 interim period.
-- RSN values sourced from legislature.ky.gov SharePoint ImportedCommittees list.
-- ON CONFLICT DO NOTHING → safe to re-run; already-present rows are untouched.

INSERT INTO public.ky_committees
  (lrc_rsn, committee_type, name, chamber, slug, profile_url)
VALUES
  -- ── Interim Joint Committees (type = 'IJ') ───────────────────────────────
  (302, 'IJ', 'Interim Joint Committee on Agriculture',
              'joint', 'interim-joint-agriculture',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=302&CommitteeType=IJ'),
  (26,  'IJ', 'Interim Joint Committee on Banking and Insurance',
              'joint', 'interim-joint-banking-insurance',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=26&CommitteeType=IJ'),
  (29,  'IJ', 'Interim Joint Committee on Education',
              'joint', 'interim-joint-education',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=29&CommitteeType=IJ'),
  (410, 'IJ', 'Interim Joint Committee on Families and Children',
              'joint', 'interim-joint-families-children',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=410&CommitteeType=IJ'),
  (407, 'IJ', 'Interim Joint Committee on Health Services',
              'joint', 'interim-joint-health-services',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=407&CommitteeType=IJ'),
  (8,   'IJ', 'Interim Joint Committee on Judiciary',
              'joint', 'interim-joint-judiciary',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=8&CommitteeType=IJ'),
  (53,  'IJ', 'Interim Joint Committee on Licensing, Occupations, and Administrative Regulations',
              'joint', 'interim-joint-licensing-occupations',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=53&CommitteeType=IJ'),
  (27,  'IJ', 'Interim Joint Committee on Local Government',
              'joint', 'interim-joint-local-government',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=27&CommitteeType=IJ'),
  (303, 'IJ', 'Interim Joint Committee on Natural Resources and Energy',
              'joint', 'interim-joint-natural-resources',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=303&CommitteeType=IJ'),
  (34,  'IJ', 'Interim Joint Committee on State Government',
              'joint', 'interim-joint-state-government',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=34&CommitteeType=IJ'),
  (35,  'IJ', 'Interim Joint Committee on Transportation',
              'joint', 'interim-joint-transportation',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=35&CommitteeType=IJ'),
  (203, 'IJ', 'Interim Joint Committee on Veterans, Military Affairs, and Public Protection',
              'joint', 'interim-joint-veterans-military',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=203&CommitteeType=IJ'),
  (354, 'IJ', 'Interim Joint Committee on Economic Development and Workforce Investment',
              'joint', 'interim-joint-economic-development',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=354&CommitteeType=IJ'),
  (358, 'IJ', 'Interim Joint Committee on Tourism, Small Business, and Information Technology',
              'joint', 'interim-joint-tourism-small-biz',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=358&CommitteeType=IJ'),

  -- Budget Review Subcommittees (IJ type, children of A&R)
  (11,  'IJ', 'Budget Review Subcommittee on Education',
              'joint', 'br-sub-education',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=11&CommitteeType=IJ'),
  (17,  'IJ', 'Budget Review Subcommittee on Justice and Judiciary',
              'joint', 'br-sub-justice',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=17&CommitteeType=IJ'),
  (33,  'IJ', 'Budget Review Subcommittee on Transportation',
              'joint', 'br-sub-transportation',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=33&CommitteeType=IJ'),
  (39,  'IJ', 'Budget Review Subcommittee on Economic Development and Tourism',
              'joint', 'br-sub-economic-development',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=39&CommitteeType=IJ'),
  (41,  'IJ', 'Budget Review Subcommittee on General Government',
              'joint', 'br-sub-general-government',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=41&CommitteeType=IJ'),
  (413, 'IJ', 'Budget Review Subcommittee on Health and Family Services',
              'joint', 'br-sub-health-family-services',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=413&CommitteeType=IJ'),

  -- ── Statutory Committees (type = 'S') not yet in DB ─────────────────────
  (3,   'S',  'Administrative Regulations Review Subcommittee',
              'joint', 'admin-regs-review',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=3&CommitteeType=S'),
  (9,   'S',  'Capital Planning Advisory Board',
              'joint', 'capital-planning-advisory-board',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=9&CommitteeType=S'),
  (143, 'S',  'Governmental Contract Review Committee',
              'joint', 'govt-contract-review',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=143&CommitteeType=S'),
  (120, 'S',  'Education Assessment and Accountability Review Subcommittee',
              'joint', 'education-assessment-accountability',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=120&CommitteeType=S'),
  (386, 'S',  'Commission on Race and Access to Opportunity',
              'joint', 'commission-race-access-opportunity',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=386&CommitteeType=S'),
  (385, 'S',  'Legislative Oversight and Investigations Committee',
              'joint', 'legislative-oversight-investigations',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=385&CommitteeType=S'),
  (414, 'S',  'Juvenile Justice Oversight Council',
              'joint', 'juvenile-justice-oversight',
              'https://legislature.ky.gov/Committees/committee-detail?CommitteeRSN=414&CommitteeType=S')
ON CONFLICT (lrc_rsn, committee_type) DO NOTHING;
